//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @return Success
     */
    game(tableName: string): Promise<void> {
        let url_ = this.baseUrl + "/api/table/{tableName}/game";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGame(_response);
        });
    }

    protected processGame(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    view(tableName: string, player: number): Promise<IGamePlayerView> {
        let url_ = this.baseUrl + "/api/table/{tableName}/player/{player}/view";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        if (player === undefined || player === null)
            throw new Error("The parameter 'player' must be defined.");
        url_ = url_.replace("{player}", encodeURIComponent("" + player));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processView(_response);
        });
    }

    protected processView(response: Response): Promise<IGamePlayerView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = IGamePlayerView.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IGamePlayerView>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    stack(tableName: string, player: number, body: boolean | undefined): Promise<IGamePlayerView> {
        let url_ = this.baseUrl + "/api/table/{tableName}/player/{player}/stack";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        if (player === undefined || player === null)
            throw new Error("The parameter 'player' must be defined.");
        url_ = url_.replace("{player}", encodeURIComponent("" + player));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStack(_response);
        });
    }

    protected processStack(response: Response): Promise<IGamePlayerView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = IGamePlayerView.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IGamePlayerView>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    challenge(tableName: string, player: number, body: number | undefined): Promise<IGamePlayerView> {
        let url_ = this.baseUrl + "/api/table/{tableName}/player/{player}/challenge";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        if (player === undefined || player === null)
            throw new Error("The parameter 'player' must be defined.");
        url_ = url_.replace("{player}", encodeURIComponent("" + player));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChallenge(_response);
        });
    }

    protected processChallenge(response: Response): Promise<IGamePlayerView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = IGamePlayerView.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IGamePlayerView>(null as any);
    }

    /**
     * @return Success
     */
    tablePOST(): Promise<string> {
        let url_ = this.baseUrl + "/api/Table";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTablePOST(_response);
        });
    }

    protected processTablePOST(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    players(tableName: string, body: string | undefined): Promise<number> {
        let url_ = this.baseUrl + "/api/Table/{tableName}/players";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPlayers(_response);
        });
    }

    protected processPlayers(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }

    /**
     * @return Success
     */
    tableGET(tableName: string): Promise<ITableView> {
        let url_ = this.baseUrl + "/api/Table/{tableName}";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTableGET(_response);
        });
    }

    protected processTableGET(response: Response): Promise<ITableView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ITableView.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ITableView>(null as any);
    }
}

export class IGamePlayerView implements IIGamePlayerView {
    readonly playerId?: number;
    readonly nextPlayer?: number;
    readonly opponentStates?: IOpponentState[] | undefined;
    hand?: IReadOnlyHand;
    readonly playedCoasters?: boolean[] | undefined;

    constructor(data?: IIGamePlayerView) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).playerId = _data["playerId"];
            (<any>this).nextPlayer = _data["nextPlayer"];
            if (Array.isArray(_data["opponentStates"])) {
                (<any>this).opponentStates = [] as any;
                for (let item of _data["opponentStates"])
                    (<any>this).opponentStates!.push(IOpponentState.fromJS(item));
            }
            this.hand = _data["hand"] ? IReadOnlyHand.fromJS(_data["hand"]) : <any>undefined;
            if (Array.isArray(_data["playedCoasters"])) {
                (<any>this).playedCoasters = [] as any;
                for (let item of _data["playedCoasters"])
                    (<any>this).playedCoasters!.push(item);
            }
        }
    }

    static fromJS(data: any): IGamePlayerView {
        data = typeof data === 'object' ? data : {};
        let result = new IGamePlayerView();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["playerId"] = this.playerId;
        data["nextPlayer"] = this.nextPlayer;
        if (Array.isArray(this.opponentStates)) {
            data["opponentStates"] = [];
            for (let item of this.opponentStates)
                data["opponentStates"].push(item.toJSON());
        }
        data["hand"] = this.hand ? this.hand.toJSON() : <any>undefined;
        if (Array.isArray(this.playedCoasters)) {
            data["playedCoasters"] = [];
            for (let item of this.playedCoasters)
                data["playedCoasters"].push(item);
        }
        return data;
    }
}

export interface IIGamePlayerView {
    playerId?: number;
    nextPlayer?: number;
    opponentStates?: IOpponentState[] | undefined;
    hand?: IReadOnlyHand;
    playedCoasters?: boolean[] | undefined;
}

export class IOpponentHand implements IIOpponentHand {
    readonly cardCount?: number;
    readonly playerId?: number;

    constructor(data?: IIOpponentHand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).cardCount = _data["cardCount"];
            (<any>this).playerId = _data["playerId"];
        }
    }

    static fromJS(data: any): IOpponentHand {
        data = typeof data === 'object' ? data : {};
        let result = new IOpponentHand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["cardCount"] = this.cardCount;
        data["playerId"] = this.playerId;
        return data;
    }
}

export interface IIOpponentHand {
    cardCount?: number;
    playerId?: number;
}

export class IOpponentState implements IIOpponentState {
    readonly playerId?: number;
    hand?: IOpponentHand;
    readonly stackCount?: number;

    constructor(data?: IIOpponentState) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).playerId = _data["playerId"];
            this.hand = _data["hand"] ? IOpponentHand.fromJS(_data["hand"]) : <any>undefined;
            (<any>this).stackCount = _data["stackCount"];
        }
    }

    static fromJS(data: any): IOpponentState {
        data = typeof data === 'object' ? data : {};
        let result = new IOpponentState();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["playerId"] = this.playerId;
        data["hand"] = this.hand ? this.hand.toJSON() : <any>undefined;
        data["stackCount"] = this.stackCount;
        return data;
    }
}

export interface IIOpponentState {
    playerId?: number;
    hand?: IOpponentHand;
    stackCount?: number;
}

export class IPlayer implements IIPlayer {
    readonly name?: string | undefined;
    readonly playerId?: number;

    constructor(data?: IIPlayer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).name = _data["name"];
            (<any>this).playerId = _data["playerId"];
        }
    }

    static fromJS(data: any): IPlayer {
        data = typeof data === 'object' ? data : {};
        let result = new IPlayer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["playerId"] = this.playerId;
        return data;
    }
}

export interface IIPlayer {
    name?: string | undefined;
    playerId?: number;
}

export class IReadOnlyHand implements IIReadOnlyHand {
    readonly cardCount?: number;
    readonly playerId?: number;
    readonly hasSkull?: boolean;

    constructor(data?: IIReadOnlyHand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).cardCount = _data["cardCount"];
            (<any>this).playerId = _data["playerId"];
            (<any>this).hasSkull = _data["hasSkull"];
        }
    }

    static fromJS(data: any): IReadOnlyHand {
        data = typeof data === 'object' ? data : {};
        let result = new IReadOnlyHand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["cardCount"] = this.cardCount;
        data["playerId"] = this.playerId;
        data["hasSkull"] = this.hasSkull;
        return data;
    }
}

export interface IIReadOnlyHand {
    cardCount?: number;
    playerId?: number;
    hasSkull?: boolean;
}

export class ITableView implements IITableView {
    readonly name?: string | undefined;
    readonly players?: IPlayer[] | undefined;

    constructor(data?: IITableView) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            (<any>this).name = _data["name"];
            if (Array.isArray(_data["players"])) {
                (<any>this).players = [] as any;
                for (let item of _data["players"])
                    (<any>this).players!.push(IPlayer.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ITableView {
        data = typeof data === 'object' ? data : {};
        let result = new ITableView();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        if (Array.isArray(this.players)) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item.toJSON());
        }
        return data;
    }
}

export interface IITableView {
    name?: string | undefined;
    players?: IPlayer[] | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}