//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IClient {

    /**
     * @return Success
     */
    game(tableName: string): Promise<void>;

    /**
     * @return Success
     */
    view(tableName: string, player: number): Promise<IGamePlayerView>;

    /**
     * @param body (optional) 
     * @return Success
     */
    stack(tableName: string, player: number, body: boolean | undefined): Promise<IGamePlayerView>;

    /**
     * @param body (optional) 
     * @return Success
     */
    challenges(tableName: string, body: PlayerBid | undefined): Promise<IGamePlayerView>;

    /**
     * @param body (optional) 
     * @return Success
     */
    reveals(tableName: string, body: PlayerBid | undefined): Promise<IGamePlayerView>;

    /**
     * @return Success
     */
    tablePOST(): Promise<string>;

    /**
     * @param body (optional) 
     * @return Success
     */
    players(tableName: string, body: string | undefined): Promise<number>;

    /**
     * @return Success
     */
    tableGET(tableName: string): Promise<ITableView>;
}

export class Client implements IClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @return Success
     */
    game(tableName: string): Promise<void> {
        let url_ = this.baseUrl + "/api/table/{tableName}/game";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGame(_response);
        });
    }

    protected processGame(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    view(tableName: string, player: number): Promise<IGamePlayerView> {
        let url_ = this.baseUrl + "/api/table/{tableName}/player/{player}/view";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        if (player === undefined || player === null)
            throw new Error("The parameter 'player' must be defined.");
        url_ = url_.replace("{player}", encodeURIComponent("" + player));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processView(_response);
        });
    }

    protected processView(response: Response): Promise<IGamePlayerView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IGamePlayerView;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IGamePlayerView>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    stack(tableName: string, player: number, body: boolean | undefined): Promise<IGamePlayerView> {
        let url_ = this.baseUrl + "/api/table/{tableName}/player/{player}/stack";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        if (player === undefined || player === null)
            throw new Error("The parameter 'player' must be defined.");
        url_ = url_.replace("{player}", encodeURIComponent("" + player));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStack(_response);
        });
    }

    protected processStack(response: Response): Promise<IGamePlayerView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IGamePlayerView;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IGamePlayerView>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    challenges(tableName: string, body: PlayerBid | undefined): Promise<IGamePlayerView> {
        let url_ = this.baseUrl + "/api/table/{tableName}/challenges";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChallenges(_response);
        });
    }

    protected processChallenges(response: Response): Promise<IGamePlayerView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IGamePlayerView;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IGamePlayerView>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    reveals(tableName: string, body: PlayerBid | undefined): Promise<IGamePlayerView> {
        let url_ = this.baseUrl + "/api/table/{tableName}/reveals";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReveals(_response);
        });
    }

    protected processReveals(response: Response): Promise<IGamePlayerView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as IGamePlayerView;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IGamePlayerView>(null as any);
    }

    /**
     * @return Success
     */
    tablePOST(): Promise<string> {
        let url_ = this.baseUrl + "/api/Table";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTablePOST(_response);
        });
    }

    protected processTablePOST(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as string;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    players(tableName: string, body: string | undefined): Promise<number> {
        let url_ = this.baseUrl + "/api/Table/{tableName}/players";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPlayers(_response);
        });
    }

    protected processPlayers(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as number;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(null as any);
    }

    /**
     * @return Success
     */
    tableGET(tableName: string): Promise<ITableView> {
        let url_ = this.baseUrl + "/api/Table/{tableName}";
        if (tableName === undefined || tableName === null)
            throw new Error("The parameter 'tableName' must be defined.");
        url_ = url_.replace("{tableName}", encodeURIComponent("" + tableName));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processTableGET(_response);
        });
    }

    protected processTableGET(response: Response): Promise<ITableView> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ITableView;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ITableView>(null as any);
    }
}

export interface IGamePlayerView {
    readonly playerId?: number;
    readonly nextPlayer?: number;
    readonly opponentStates?: IOpponentState[] | null;
    hand?: IReadOnlyHand;
    readonly playedCoasters?: boolean[] | null;
    readonly phase?: string | null;
    readonly bids?: IPlayerBid[] | null;
}

export interface IOpponentHand {
    readonly cardCount?: number;
    readonly playerId?: number;
}

export interface IOpponentState {
    readonly playerId?: number;
    hand?: IOpponentHand;
    readonly stackCount?: number;
    readonly reveals?: boolean[] | null;
}

export interface IPlayer {
    readonly name?: string | null;
    readonly playerId?: number;
}

export interface IPlayerBid {
    bid?: number | null;
    playerId?: number;
}

export interface IReadOnlyHand {
    readonly cardCount?: number;
    readonly playerId?: number;
    readonly hasSkull?: boolean;
}

export interface ITableView {
    readonly name?: string | null;
    readonly players?: IPlayer[] | null;
}

export interface PlayerBid {
    playerId?: number;
    bid?: number | null;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}